apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.imagestream.name }}
  namespace: {{ .Values.namespace }}
spec:
  lookupPolicy:
    local: {{ .Values.imagestream.spec.lookupPolicy.local }}
  tags: 
    - name: "{{ .Values.imagestream.spec.tags.name }}"
      from:
        kind: {{ .Values.imagestream.spec.tags.from.kind }}
        name: {{ .Values.imagestream.spec.tags.from.name }}
      referencePolicy:
        type: {{ .Values.imagestream.spec.tags.referencePolicy.type }}
      importPolicy:
        scheduled: {{ .Values.imagestream.spec.tags.importPolicy.scheduled }}