apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypersvolume
  namespace: "{{ .Values.namespace }}"
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/TestPV/"