apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvclaim
  namespace: "{{ .Values.namespace }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi