apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ .Release.Name }}-route"
  namespace: {{ .Values.namespace }}
spec:
  to:
    kind: {{ .Values.route.spec.kind }}
    name: "{{ .Release.Name }}-service"
  host: {{ .Values.route.host }}
  path: {{ .Values.route.path }}
  port:
    targetPort: {{ .Values.route.port.targetPort }}
  tls:
    termination: {{ .Values.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.tls.insecureEdgeTerminationPolicy }}
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIDqzCCApOgAwIBAgIUUP1QzRr85qT/ofZNCIa+NnXgbNEwDQYJKoZIhvcNAQEL
      BQAwZTELMAkGA1UEBhMCSVQxCzAJBgNVBAgMAklUMQ0wCwYDVQQHDARSb21lMSEw
      HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQxFzAVBgNVBAMMDnBhZ2lu
      YXRlLmxvY2FsMB4XDTI0MTIxNTIxMzYzNFoXDTM0MTIxMzIxMzYzNFowZTELMAkG
      A1UEBhMCSVQxCzAJBgNVBAgMAklUMQ0wCwYDVQQHDARSb21lMSEwHwYDVQQKDBhJ
      bnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQxFzAVBgNVBAMMDnBhZ2luYXRlLmxvY2Fs
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA37JfGR9AGmJsNGvXQqeb
      jS/ZwMXZdHuZPKvoX1pCCo9dS+SC0dfHv2XTpEQJoBQDbILlypjdd3fDrj9mh2AY
      LFVL86surIi9wCg03mc2DxR5+D190mGh6G9HT936jouQZxHby5iIubsX3D/j77f3
      e7tzI8+Gi/kNMRqkex7I6Dff+deJc9UntDm/76ZmXpPTA8ogS5Q7xn7840Js5gZz
      mtAh1991gT+cubn1Dbb1ccRaKxaLtZB5bFiiaMR2yFb/JMPaEhEppAwozygrOiMw
      ztRRL/MhQfHGOuH1yFQJs7kwQnJGu+N/5sXI9NFHK+PfAm5XqAv6nMu8k1es9q9D
      EQIDAQABo1MwUTAdBgNVHQ4EFgQUSHEuiWuKKxr8AmgNzuQT0UOPYowwHwYDVR0j
      BBgwFoAUSHEuiWuKKxr8AmgNzuQT0UOPYowwDwYDVR0TAQH/BAUwAwEB/zANBgkq
      hkiG9w0BAQsFAAOCAQEAdcsTh4vltyXz6aXX4fvkMufNuVCfqhowzISX0mhyJs7u
      DpktaYTcTZOCNyJkJKml3Vjp/MwKAKUY9wK6IYgK7754BcrkFKxdb4fvPzH3EiKB
      Kp8/Z90TjE46ZT7+5N8LTwF8enL8/4yyu4UN/MjEt6Y+yO7HDrFGrTf5pdNtC1lB
      xKAASSuymHQJbodT/6RCnlYN12vA1rT2BT8PYDYcYFRt0Kfe8UaC8sUakQ8qWWUk
      8do67pR+IDRxlaVRVPSMcLeOPVABxCZYwYCVm3OB5KLUuJzhcuUqwpLLLiLGoq4N
      589NRY9qY4N1BLDGAlhipVibZPzikUXb/iswoX2krA==
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDfsl8ZH0AaYmw0
      a9dCp5uNL9nAxdl0e5k8q+hfWkIKj11L5ILR18e/ZdOkRAmgFANsguXKmN13d8Ou
      P2aHYBgsVUvzqy6siL3AKDTeZzYPFHn4PX3SYaHob0dP3fqOi5BnEdvLmIi5uxfc
      P+Pvt/d7u3Mjz4aL+Q0xGqR7HsjoN9/514lz1Se0Ob/vpmZek9MDyiBLlDvGfvzj
      QmzmBnOa0CHX33WBP5y5ufUNtvVxxForFou1kHlsWKJoxHbIVv8kw9oSESmkDCjP
      KCs6IzDO1FEv8yFB8cY64fXIVAmzuTBCcka743/mxcj00Ucr498CbleoC/qcy7yT
      V6z2r0MRAgMBAAECggEAA4iH5lfZ2tuAIF8tshX/Un5q1EKBGfe+fA4DvccpW40C
      fmmNxBkXmhyBIyCXUv8jQ1+ul9ch9GT2DcwJkgzWBOk/VF95UsIBgUYBTnFXPMC9
      i8q+MIhYltkfHryqXFMJr7RsAi4WxsbqQbvZSAGMuAMbdqQsrgxRMDE0Cjp6a5SN
      c4xsVkKNj3L7Y2dC6DzcdTbwupXNnuwEpkWTn7O694TyrGux5dBsWI/yQmxl+qF9
      AWND1kxZq3VmxW6rczRn32EisDMroQGHxhTx8gqnuxpTsoPk0HYsffuQMA9uTtM+
      4U5wSPXBgUebDvbYNeT2f2tFHP59DUapC61M3Cr5mwKBgQD9O1uUNBfKzZbJHdvC
      TWhWds5EtQN5otPw+Mhv3t1z5AK6WBe0dzUCjsJRsC2CF2IEGbWNSl86U1TVXwdG
      /iyzaOXKb+cBpMZ987d/7XMPFEvV7Rpjwtn6WLNJ+Jwp/gNgbeuFJVJvkQmTV3Y+
      UVHFFk6Q/kLVEZGHwDJ1fwB+CwKBgQDiJFzol1p8bnpdOzq3UNNGSkdCDDuNfZHY
      XStUoMWAAK9EnuP91RSUEj9GyFU2GNtbf3xOcmZ3PdhswSuN4N7O24+7TXUB/hQj
      OZE5VllidVCufe330DYaPWxp3+Mkr26UN527mHPZd0zBxu0wUm27sBY/Mw4Xdu/v
      lDQgzlIg0wKBgELhk31gCMyiYem6PhliUmVLuYzB9ioBDFL/kgih5wE9vk6zB4e9
      WD3VsJLcohhSzqtgkue/Ncl0ytoT4Bsq9GlqEg7WYT+44kfPv65E63eXF7Rni+m/
      Q8zv8mJeC/i3QvML9QFUayJWPx4wImWxGpSgIJ4A2Wvm2PXumCUaJuojAoGBALfp
      4NGcfg+ifcui5t69UgXhVNCHSEuK6vju1NWPpu+yHtiM7Fi8WW8O4/054esMDiH8
      rWjTKzggyQmxlC1fy3SqJdurY9SKAXCgWdYqvqkPRd2TNtyKreVrPOdiGMX2EtVh
      4dr2Yolit78EfFQHRY0V6RHfAL/ej8XlXvurMCnXAoGBAOSkuHLr5SNKDwRrxWrw
      ZcqT1YC4LuefUKV8GHOYHrUicyetlJDvI03vOgPc+G1JR2rgH/TtqBh5y+As4nLL
      ht+p2C8PCsiYs/gIr7FUIQSkZOE/RD+Zo5KRD/vrNAMLF2lK51n+gZ6B1Yu+TLp5
      Zi9WFOruUO3yc3fSw8lvJfAJ
      -----END PRIVATE KEY-----