
replicaCount: 1

namespace: ttrivelli

container:
  port_name: http  
  port: 8000
  protocol: TCP

resources:
  requests:
    memory: "256Mi"
    cpu: "0.5"
  limits:
    memory: "512Mi"
    cpu: "0.5"  

livenessProbe:
  httpGet: 
    path: /
    port: 8000
  initialDelaySeconds: 10
  PeriodSeconds: 15
  timeoutSeconds: 3
  failureThreshold: 5
  successThreshold: 1

readinessProbe:
  httpGet: 
    path: /
    port: 8000
  initialDelaySeconds: 10
  PeriodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 5
  successThreshold: 1

service:
  type: NodePort
  port: 8000
  
#ROUTE 

route:
  spec:
    kind: Service
  host: paginatest.local
  path: /
  port:
    targetPort: 8000

tls:
  termination: edge
  insecureEdgeTerminationPolicy: Redirect

imagestream:
  name: imagestreams
  spec:
    lookupPolicy:
      local: false
    tags: 
      name: 0.1
      from:
        kind: DockerImage
        name: t0mx2as0/os4exercise:latest
      referencePolicy:
        type: Source
      importPolicy:
        scheduled: true